name: "tfupdate"

on:
  workflow_dispatch: null
jobs:
  update_terraform_versions:
    timeout-minutes: 30
    name: Update terraform versions
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false

      - name: tfupdate
        uses: daisaru11/tfupdate-github-actions@be636ef891d6ef9f1efd0e1f9f0d10e3e995c192 # v1
        with:
          tfupdate_subcommand: terraform
          tfupdate_path: "."
