name: "tfupdate"

on:
  workflow_dispatch: null
jobs:
  update_terraform_versions:
    timeout-minutes: 30
    name: Update terraform versions
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: tfupdate
        uses: daisaru11/tfupdate-github-actions@v1
        with:
          tfupdate_subcommand: terraform
          tfupdate_path: "."
